In [1]:
import numpy as np

In [155]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [158]:
a[a < 0]

array([-2, -1, -6, -7])

In [79]:
# 1. How many negative numbers are there?
np.count_nonzero(a < 0)

4

In [140]:
# another way
# mask = a < 0
# mask
# len(a[mask])

4

In [141]:
# another way
# mask = (a < 0)
# (a < 0).sum()

4

In [93]:
# 2. How many positive numbers are there?
np.count_nonzero(a > 0)

5

In [101]:
# 3. How many even positive numbers are there?
mask = (a % 2 == 0) & (a > 0)
np.count_nonzero(a[mask])

3

10

In [144]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?
np.count_nonzero(a + 3)

12

In [143]:
((a + 3) > 0).sum()

10

In [75]:
# 5. If you squared each number, what would the new mean and standard deviation be?
a ** 2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [90]:
np.mean(a ** 2)

74.0

In [89]:
np.std(a ** 2)

144.0243035046516

In [146]:
# # 6. A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set. 
# See this link for more on centering.

centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [147]:
centered.mean()

0.0

In [108]:
np.std(a)

8.06225774829855

In [110]:
np.mean(a)

3.0

In [149]:
# 7. Calculate the z-score for each data point. Recall that the z-score
z_score = (a - a.mean()) / a.std()
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
# # 8. Copy the setup and exercise directions from More Numpy Practice into 
# your numpy_exercises.py and add your solutions.


In [ ]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# # Use python's built in functionality/operators to determine the following:
# # Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers 
# in above list

new_a = np.array(a)
new_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
sum_of_a = new_a.sum()
sum_of_a

55

In [8]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers 
# in the above list
min_of_a = new_a.min()
min_of_a

1

In [10]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers 
# in the above list
max_of_a = new_a.max()
max_of_a

10

In [14]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers 
# in the above list
mean_of_a = new_a.mean()
mean_of_a

5.5

In [20]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying 
# all the numbers in the above list together
product_of_a = new_a.prod()
product_of_a

3628800

In [30]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a 
# squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [34]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
mask = (new_a % 2 != 0)
odds_in_a = new_a[mask]
odds_in_a

array([1, 3, 5, 7, 9])

In [36]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
mask = (new_a % 2 != 1)
evens_in_a = new_a[mask]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [20]:
import numpy as np
b = [
    [3, 4, 5],
    [6, 7, 8]
]
new_b = np.array(b)
new_b

array([[3, 4, 5],
       [6, 7, 8]])

In [151]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)
np.sum(new_b)

33

In [152]:
new_b.sum()

33

In [153]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
np.min(new_b)

3

In [126]:
min(new_b[0])

3

In [21]:
new_b

array([[3, 4, 5],
       [6, 7, 8]])

In [23]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
np.max(new_b)

8

In [22]:
# 4. # Exercise 4 - refactor the following using numpy to find the mean of b
np.mean(new_b)

5.5

In [3]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number
np.prod(new_b) 

20160

In [4]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)
np.square(new_b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [6]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)
new_b [new_b % 2 != 0]

array([3, 5, 7])

In [7]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)
new_b [new_b % 2 != 1]

array([4, 6, 8])

In [8]:
# Exercise 9 - print out the shape of the array b.
new_b.shape

(2, 3)

In [9]:
# Exercise 10 - transpose the array b.
new_b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [11]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
np.reshape(new_b, (1, 6))

array([[3, 4, 5, 6, 7, 8]])

In [12]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
np.reshape(new_b, (6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
# ## Setup 3
# c = [
#     [1, 2, 3],
#     [4, 5, 6],
#     [7, 8, 9]
# ]

# # HINT, you'll first need to make sure that the "c" variable is a numpy array prior to 
# using numpy array methods.
# # Exercise 1 - Find the min, max, sum, and product of c.

# # Exercise 2 - Determine the standard deviation of c.

# # Exercise 3 - Determine the variance of c.

# # Exercise 4 - Print out the shape of the array c

# # Exercise 5 - Transpose c and print out transposed result.

# # Exercise 6 - Get the dot product of the array c with c. 

# # Exercise 7 - Write the code necessary to sum up the result of c times c transposed. 
# Answer should be 261

# # Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
# Answer should be 131681894400.

In [14]:
import numpy as np
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to 
# using numpy array methods.
# # Exercise 1 - Find the min, max, sum, and product of c.
new_c = np.array(c)
new_c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
new_c.min(), new_c.max(), new_c.sum(), new_c.prod()

(1, 9, 45, 362880)

In [19]:
np.min(new_c), np.max(new_c), np.sum(new_c), np.prod(new_c)

(1, 9, 45, 362880)

In [15]:
# Exercise 2 - Determine the standard deviation of c.
np.std(new_c)

2.581988897471611

In [20]:
# Exercise 3 - Determine the variance of c.
np.var(new_c)

6.666666666666667

In [21]:
# Exercise 4 - Print out the shape of the array c
np.shape(new_c)

(3, 3)

In [22]:
new_c.shape

(3, 3)

In [24]:
# Exercise 5 - Transpose c and print out transposed result.
new_c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(new_c, new_c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [29]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. 
# Answer should be 261
new_c.T * new_c

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [30]:
(new_c.T * new_c).sum()

261

In [32]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
# Answer should be 131681894400.
(new_c.T * new_c).prod()

131681894400

In [ ]:
# Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [33]:
import numpy as np
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
# Exercise 1 - Find the sine of all the numbers in d
new_d = np.array(d)
new_d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [35]:
np.sin(new_d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [37]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(new_d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [38]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(new_d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [39]:
# Exercise 4 - Find all the negative numbers in d
new_d [new_d < 0]

array([-90, -30, -45, -45])

In [40]:
# Exercise 5 - Find all the positive numbers in d
new_d [new_d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [41]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(new_d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [42]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(new_d))

11

In [43]:
# Exercise 8 - Print out the shape of d.
np.shape(new_d)

(3, 6)

In [45]:
new_d.shape

(3, 6)

In [47]:
# Exercise 9 - Transpose and then print out the shape of d.
new_d.T.shape

(6, 3)

In [49]:
# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(new_d, (9, 2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])